image:
  file: .github/dockerfiles/Dockerfile.gitpod-base
  context: .
tasks:
  - name: Prep Collator
    init: bash ./scripts/prep-collator.sh main
    # Todo: Tail logs
  - name: Prep relay 
    init: bash ./scripts/prep-relay.sh main
    # Todo: Tail logs
  - name: Test Net
    init:  gp sync-await collator && gp sync-await relay 
    command: zombienet spawn zombienet/config.toml -p native

github:
  prebuilds:
    development: true
ports:
  - port: 8844
    visibility: public
  - port: 9944
    visibility: public