image:
  file: .github/dockerfiles/Dockerfile.gitpod-base
  context: .
tasks:
  - name: Collator
    init: bash ./scripts/prep-collator.sh main && gp sync-await relay
    command: ./scripts/start-collator.sh
  - name: Relay Alice 
    init: bash ./scripts/prep-relay.sh
    command: bash ./scripts/start-relay.sh
  - name: Relay Bob
    # Wait for alice
    init: gp sync-await relay
    command: bash ./scripts/start-relay.sh
  # - name: Test Net
  #   init:  gp sync-await collator && gp sync-await relay 
  #   command: zombienet spawn zombienet/config.toml -p native


