image:
  file: .github/dockerfiles/Dockerfile.gitpod-base
  context: .
tasks:
  - name: Init bins
    init: docker build --pull --rm -f ".github/dockerfiles/Dockerfile.collator" -t chocnet/parachain-collator "."
    command: ./target/debug/parachain-collator
  - name: Relay
    init: |
      sh ./scripts/prep-bins.sh 
      docker build --pull --rm -f ".github/dockerfiles/Dockerfile.relay" -t chocnet/polkadot-debug "."
      rm -r bins



