[settings]
timeout = 1000

[relaychain]
default_image = "chocnet/polkadot-debug:latest"
default_command = "./bins/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 2000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "chocnet/parachain-collator:latest"
  command = "./bins/parachain-collator"
  args = ["-lparachain=debug"]
