[settings]
timeout = 1000

[relaychain]
default_image = "chocnet/polkadot-debug:latest"
default_command = "/home/gitpod/relay/polkadot/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 2000

  [parachains.collator]
  name = "collator01"
  image = "chocnet/parachain-collator:latest"
  command = "./target/debug/parachain-collator"
  args = ["-lparachain=debug"]
