FROM gitpod/workspace-full

# Change to machine user/group
ARG USER=gitpod
ARG GROUP=gitpod
USER ${USER}:${GROUP}

EXPOSE 30333 9933 9944

ARG COLLATOR_BIN=./target/debug/parachain-collator

COPY ${COLLATOR_BIN} /usr/local/bin

ENTRYPOINT ["/usr/local/bin/parachain-collator"]
